### PR TITLE
Architecture redesign: Child Modules and LazyLoading

### PR DESCRIPTION
**Pull request by aalmajanob**
Now the application includes one root Module (AppModule) and different child Modules (one per scope).
This allows us to use LazyLoading approach: loading modules under demand, when required,  improving scalability and loading size/times.

### CODE REVIEW

**Comment by aalmajanob** [comment]
Hi Roberto,

  I´m not sure if I followed your steps correctly, but the changes should properly work (at least at my environment :))

  What is your opinion about the new approach? I hope you find it interesting. It does not have any performance impact at this moment due to the small size of the app, but I´m currently using this approach in a bigger development and it reduces significantly loading times / sizes.

  Regards,
Andrés.

**Comment by robisim74** [comment]
Hi Andrés, thanks a lot for this pr. Yes, lazy loading is important in a real scenario. I'm off-line these days. I'll see the commit as soon as possible. Greetings

**Comment by robisim74** [comment]
Hi Andrés, finally I did the merge of your pr. I had to remove some unnecessary files and uniformize the style. I fixed auth guard and added preloading strategy for all modules: https://github.com/robisim74/AngularSPAWebAPI/pull/18/commits/3640fd5fe5ebbf91fdfb51ed3605c3733cbba48c
Thank you again a lot for your work!
Greetings,
Roberto

**Comment by aalmajanob** [comment]
Hi Roberto,

  You are welcome! :)

  P.D: good idea the preloading strategy, I have just tok a look and seems to be an interesting feature.

**Pull request merged**
